### ISSUE TITLE
Test script: ModuleNotFoundError: No module named 'parmap'

### ISSUE THREAD

**Issue by Gabriel-p** [pmelchior/pygmmis#14]
Running the [test script](https://github.com/pmelchior/pygmmis/blob/master/tests/test.py) results in:

```
initializing spheres with s=3.13 near data points
ITER    SAMPLES LOG_L   STTraceback (most recent call last):
  File "/home/gabriel/Descargas/pygmmis_test.py", line 254, in <module>
    l[r], _ = pygmmis.fit(gmms[r], data, w=w, cutoff=cutoff, background=bg, rng=rng)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/pygmmis.py", line 667, in fit
    log_L, N, N2 = _EM(gmm, log_p, U, T_inv, log_S, H, data_, covar=covar_, R=R, sel_callback=sel_callback, oversampling=oversampling, covar_callback=covar_callback, w=w, pool=pool, chunksize=chunksize, cutoff=cutoff, background=background, p_bg=p_bg, changeable=changeable, maxiter=maxiter, tol=tol, rng=rng)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/pygmmis.py", line 770, in _EM
    log_L_, N, N2, N0 = _EMstep(gmm, log_p, U, T_inv, log_S, H, N0, data, covar=covar, R=R,  sel_callback=sel_callback, oversampling=oversampling, covar_callback=covar_callback, background=background, p_bg=p_bg , w=w, pool=pool, chunksize=chunksize, cutoff=cutoff_nd, tol=tol, changeable=changeable, it=it, rng=rng)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/pygmmis.py", line 828, in _EMstep
    log_L = _Estep(gmm, log_p, U, T_inv, log_S, H, data, covar=covar, R=R, background=background, p_bg=p_bg, pool=pool, chunksize=chunksize, cutoff=cutoff, it=it)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/pygmmis.py", line 886, in _Estep
    import parmap
ModuleNotFoundError: No module named 'parmap'
bind: Invalid command `enable-meta-key'.
```

Installing `parmap` obviously solves the issue.

**Comment by pmelchior** [comment]
Thanks for the report. How did you install pygmmis: From pip or a by `python setup.py install`?

**Comment by Gabriel-p** [comment]
I used `pip` inside a `conda` environment. I can give you the full details of the environment if you need it.
