### ISSUE TITLE
Can't install via pip: multiprocessing is already present in Python 3

### ISSUE THREAD

**Issue by Gabriel-p** [pmelchior/pygmmis#15]
```
$ pip install pygmmis
Collecting pygmmis
  Using cached pygmmis-1.1.3-py2.py3-none-any.whl (22 kB)
Requirement already satisfied: numpy in /home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages (from pygmmis) (1.18.1)
Collecting parmap
  Using cached parmap-1.5.2-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: scipy in /home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages (from pygmmis) (1.4.1)
Collecting multiprocessing
  Using cached multiprocessing-2.6.2.1.tar.gz (108 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/gabriel/miniconda3/envs/py3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-redkuhhn/multiprocessing/setup.py'"'"'; __file__='"'"'/tmp/pip-install-redkuhhn/multiprocessing/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-redkuhhn/multiprocessing/pip-egg-info
         cwd: /tmp/pip-install-redkuhhn/multiprocessing/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-redkuhhn/multiprocessing/setup.py", line 94
        print 'Macros:'
                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Macros:')?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

According to [this SO post](https://stackoverflow.com/a/42653828/1391441), `multiprocessing` is already included in Python 3.

**Comment by pmelchior** [comment]
Thanks for the link. It shows that the package is quite old.., but the fix is simple.
